/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

uint32_t RCC_BaseAddress = 0x40023800U;
uint32_t RCC_OffSet = 0x30U;
uint32_t GPIOx_BaseAddress = 0x40020C00U;
uint32_t GPIOx_IDR_OffSet = 0x10U;
uint32_t GPIOx_BSRR_OffSet = 0x18U;
uint32_t GPIOA_BaseAddress = 0x40020000U;
uint32_t SYST_CSR_Address = 0xE000E010U;
uint32_t SYST_RVR_Address = 0xE000E014U;
uint32_t SYST_CVR_Address = 0xE000E018U;

volatile uint32_t system_ticks = 0U;

typedef enum
{
    GAME_READY,
    GAME_WAITING,
    GAME_MEASURING,
    GAME_RESULT,
	GAME_WAIT_RELEASE,
	GAME_TOO_SOON
} game_state_t;


void led_init(void);
void button_init(void);
void systick_init(void);
void led_on(void);
void led_off(void);
uint8_t button_is_pressed(void);

int main(void)
{
	led_init();
	button_init();
	led_off();
	systick_init();

	game_state_t game_state = GAME_READY;

	uint32_t wait_start_tick = 0U;
	uint32_t reaction_start_tick = 0U;
	uint32_t reaction_time_ms = 0U;

	for(;;)
	{
		switch(game_state)
		{
			case GAME_READY:
				if(button_is_pressed() == 1U)
				{
					game_state = GAME_WAIT_RELEASE;
				}
				break;

			case GAME_WAIT_RELEASE:
				if(button_is_pressed() == 0U)
				{
					wait_start_tick = system_ticks;
					game_state = GAME_WAITING;
				}
				break;

			case GAME_WAITING:
				if(button_is_pressed() == 1U)
				{
					game_state = GAME_TOO_SOON;

				}
				else if((system_ticks - wait_start_tick) >= 2000U)
				{
					led_on();
					reaction_start_tick = system_ticks;
					game_state = GAME_MEASURING;
				}
				break;

			case GAME_MEASURING:
				if(button_is_pressed() == 1U)
				{
					reaction_time_ms = system_ticks - reaction_start_tick;
					printf("Reaction time: %lu ms\n", (unsigned long)reaction_time_ms);
					led_off();
					game_state = GAME_RESULT;
				}
				break;

			case GAME_RESULT:
				if(button_is_pressed() == 0U)
				{
					game_state = GAME_READY;
				}
				break;

			case GAME_TOO_SOON:
				if(button_is_pressed() == 0U)
				{
					printf("Too soon!\n");
					game_state = GAME_READY;
				}
				break;

			default:
				break;
		}
	}
}

void led_init(void)
{
	volatile uint32_t *pRCC_AHB1ENR_GPIODEN = (uint32_t*)(RCC_BaseAddress + RCC_OffSet);
	*pRCC_AHB1ENR_GPIODEN |= (1U << 3);

	volatile uint32_t *pGPIOD_Moder12 = (uint32_t*)(GPIOx_BaseAddress);
	*pGPIOD_Moder12 &= ~(3U << 24);
	*pGPIOD_Moder12 |= (1U << 24);

}

void button_init(void)
{
	volatile uint32_t *pRCC_AHB1ENR_GPIOAEN = (uint32_t*)(RCC_BaseAddress + RCC_OffSet);
	*pRCC_AHB1ENR_GPIOAEN |= (1U << 0);

	volatile uint32_t *pGPIOA_Moder0 = (uint32_t*)(GPIOA_BaseAddress);
	*pGPIOA_Moder0 &= ~(3U << 0);

}

void systick_init(void)
{
	volatile uint32_t *pSTK_CTRL_Enable = (uint32_t*)(SYST_CSR_Address);
	*pSTK_CTRL_Enable &= ~(1U << 0);
	volatile uint32_t *pSTK_LOAD = (uint32_t*)(SYST_RVR_Address);
	*pSTK_LOAD = 15999U;
	volatile uint32_t *pSTK_VAL = (uint32_t*)(SYST_CVR_Address);
	*pSTK_VAL = 0U;

	*pSTK_CTRL_Enable |= (1U << 2) | (1U << 1) | (1U << 0);

}

void led_on(void)
{

	volatile uint32_t *pGPIOD_BSRR = (uint32_t*)(GPIOx_BaseAddress + GPIOx_BSRR_OffSet);
	*pGPIOD_BSRR = (1U << 12);

}

void led_off(void)
{
	volatile uint32_t *pGPIOD_BSRR = (uint32_t*)(GPIOx_BaseAddress + GPIOx_BSRR_OffSet);
	*pGPIOD_BSRR = (1U << 28);
}

uint8_t button_is_pressed(void)
{
	volatile uint32_t *pGPIOA_IDR = (uint32_t*)(GPIOA_BaseAddress +GPIOx_IDR_OffSet);
	uint32_t GPIOA_IDR_value = *pGPIOA_IDR;

	uint8_t button_state = GPIOA_IDR_value & (1U << 0);

	return button_state;
}

void SysTick_Handler(void)
{
	system_ticks += 1;
}

