/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

uint32_t RCC_BaseAddress = 0x40023800U;
uint32_t RCC_OffSet = 0x30U;
uint32_t GPIOx_BaseAddress = 0x40020C00U;
uint32_t GPIOx_BSRR_OffSet = 0x18U;


void led_init(void);
void led_on(void);

int main(void)
{

	led_init();
	led_on();
	while(1);
}

void led_init(void)
{
	volatile uint32_t *pRCC_AHB1ENR = (uint32_t*)(RCC_BaseAddress + RCC_OffSet);
	//Enable clock
	*pRCC_AHB1ENR |= (1U << 3);
	volatile uint32_t *pGPIOD_Moder12 = (uint32_t*)(GPIOx_BaseAddress);

	*pGPIOD_Moder12 &= ~(3U << 24);
	*pGPIOD_Moder12 |= (1U << 24);

}

void led_on(void)
{

	volatile uint32_t *pGPIOD_BSRR = (uint32_t*)(GPIOx_BaseAddress + GPIOx_BSRR_OffSet);
	*pGPIOD_BSRR = (1U << 12);

}

void led_off(void)
{
	volatile uint32_t *pGPIOD_BSRR = (uint32_t*)(GPIOx_BaseAddress + GPIOx_BSRR_OffSet);
	*pGPIOD_BSRR = (1U << 28);
}
