/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define LIS3DSH_WHO_AM_I_ADDR 	0x0FU
#define LIS3DSH_WHO_AM_I_VALUE 	0x3FU

uint32_t RCC_BaseAddress = 0x40023800U;
uint32_t RCC_AHB1_Offset = 0x30U;
uint32_t RCC_APB2_Offset = 0x44U;
uint32_t GPIOA_BaseAddress = 0x40020000U;
uint32_t AFRL_Offset = 0x20U;
uint32_t GPIOE_BaseAddress = 0x40021000U;
uint32_t BSRR_Offset = 0x18U;
uint32_t SPI1_BaseAddress = 0x40013000U;
uint32_t SPI1_SR_Offset = 0x08U;
uint32_t SPI1_DR_Offset = 0x0CU;

void sensor_gpio_init(void);
void spi1_init(void);
uint8_t spi1_transfer(uint8_t data);
void sensor_select(void);
void sensor_deselect(void);
uint8_t sensor_read_register(uint8_t register_address);



int main(void)
{
    printf("Tilt indicator starting...\n");
    sensor_gpio_init();
    spi1_init();
    uint8_t sensor_id = sensor_read_register(LIS3DSH_WHO_AM_I_ADDR);
    printf("Sensor ID: 0x%02X\n", (unsigned int)sensor_id);
	for(;;);
}

void sensor_gpio_init(void)
{
	volatile uint32_t *pRCC_AHB1ENR = (uint32_t*)(RCC_BaseAddress + RCC_AHB1_Offset);
	*pRCC_AHB1ENR |= (1U << 0) | (1U << 4);

	volatile uint32_t *pGPIOE_BSRR = (uint32_t*)(GPIOE_BaseAddress + BSRR_Offset);
	*pGPIOE_BSRR = (1U << 3);

	volatile uint32_t *pGPIOA_Moder = (uint32_t*)(GPIOA_BaseAddress);
	*pGPIOA_Moder &= ~((3U << 10) | (3U << 12) | (3U << 14));
	*pGPIOA_Moder |= (2U << 10) | (2U << 12) | (2U << 14);

	volatile uint32_t *pGPIOE_Moder = (uint32_t*)(GPIOE_BaseAddress);
	*pGPIOE_Moder &= ~(3U << 6);
	*pGPIOE_Moder |= (1U << 6);

	volatile uint32_t *pGPIOA_AFRL = (uint32_t*)(GPIOA_BaseAddress + AFRL_Offset);
	*pGPIOA_AFRL &= ~((0xFU << 20) | (0xFU << 24) | (0xFU << 28));
	*pGPIOA_AFRL |= (5U << 20) | (5U << 24) | (5U << 28);

}

void spi1_init(void)
{
	volatile uint32_t *pRCC_APB2ENR = (uint32_t*)(RCC_BaseAddress + RCC_APB2_Offset);
	*pRCC_APB2ENR |= (1U << 12);

	volatile uint32_t *pSPI1_CR1 = (uint32_t*)(SPI1_BaseAddress);
	*pSPI1_CR1 &= ~(1U << 6);
	*pSPI1_CR1 |= (1U << 2);
	*pSPI1_CR1 &= ~(7U << 3);
	*pSPI1_CR1 |= (3U << 3);
	*pSPI1_CR1 |= (1U << 8) | (1U << 9);
	*pSPI1_CR1 |= (1U << 0) | (1U << 1);
	*pSPI1_CR1 &= ~((1U << 7) | (1U << 10) | (1U << 11) | (1U << 15));
	*pSPI1_CR1 |= (1U << 6);
}

uint8_t spi1_transfer(uint8_t data)
{
	volatile uint32_t *pSPI1_SR = (uint32_t*)(SPI1_BaseAddress + SPI1_SR_Offset);
	volatile uint8_t *pSPI1_DR = (uint8_t*)(SPI1_BaseAddress + SPI1_DR_Offset);

	while((*pSPI1_SR & (1U << 1)) == 0){}
	*pSPI1_DR = data;

	while((*pSPI1_SR & (1U << 0)) == 0){}

	return *pSPI1_DR;
}

void sensor_select(void)
{
	volatile uint32_t *pGPIOE_BSRR = (uint32_t*)(GPIOE_BaseAddress + BSRR_Offset);
	*pGPIOE_BSRR = (1U << 19);
}

void sensor_deselect(void)
{
	volatile uint32_t *pSPI1_SR = (uint32_t*)(SPI1_BaseAddress + SPI1_SR_Offset);
	while((*pSPI1_SR & (1U << 7)) != 0){}

	volatile uint32_t *pGPIOE_BSRR = (uint32_t*)(GPIOE_BaseAddress + BSRR_Offset);
	*pGPIOE_BSRR = (1U << 3);
}

uint8_t sensor_read_register(uint8_t register_address)
{
	sensor_select();
	spi1_transfer(register_address | (1U << 7));
	uint8_t register_value = spi1_transfer(0x00U);
	sensor_deselect();
	return register_value;

}


