/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define LIS3DSH_WHO_AM_I_ADDR 	0x0FU
#define LIS3DSH_WHO_AM_I_VALUE 	0x3FU
#define LIS3DSH_CTRL_REG4_ADDR	0X20U
#define LIS3DSH_OUT_X_L_ADDR 	0x28
#define LIS3DSH_OUT_X_H_ADDR 	0x29
#define TILT_THRESHOLD			2000
#define TILT_RELEASE_THRESHOLD	1500
#define SPI_TIMEOUT_MS			10U

typedef enum
{
	TILT_LEVEL,
	TILT_LEFT,
	TILT_RIGHT
} tilt_state_t;

typedef enum
{
	SPI_OK,
	SPI_TIMEOUT
} spi_status_t;

uint32_t RCC_BaseAddress = 0x40023800U;
uint32_t RCC_AHB1_Offset = 0x30U;
uint32_t RCC_APB2_Offset = 0x44U;
uint32_t GPIOA_BaseAddress = 0x40020000U;
uint32_t AFRL_Offset = 0x20U;
uint32_t GPIOE_BaseAddress = 0x40021000U;
uint32_t BSRR_Offset = 0x18U;
uint32_t SPI1_BaseAddress = 0x40013000U;
uint32_t SPI1_SR_Offset = 0x08U;
uint32_t SPI1_DR_Offset = 0x0CU;
uint32_t SYST_CSR_Address = 0xE000E010U;
uint32_t SYST_RVR_Address = 0xE000E014U;
uint32_t SYST_CVR_Address = 0xE000E018U;
uint32_t GPIOx_BaseAddress = 0x40020C00U;
uint32_t GPIOx_BSRR_Offset = 0x18U;

volatile uint32_t system_ticks = 0U;


void sensor_gpio_init(void);
void spi1_init(void);
spi_status_t spi1_transfer(uint8_t data, uint8_t *pReceived);
void sensor_select(void);
spi_status_t sensor_deselect(void);
spi_status_t sensor_read_register(uint8_t register_address,
                                  uint8_t *pValue);
spi_status_t sensor_write_register(uint8_t register_address, uint8_t value);
spi_status_t sensor_read_x(int16_t *pX);
void systick_init(void);
void SysTick_Handler(void);
void led_gpio_init(void);
void leds_show_left(void);
void leds_show_right(void);
void leds_show_level(void);




int main(void)
{
    sensor_gpio_init();
    spi1_init();
    systick_init();
    led_gpio_init();

    uint8_t sensor_id;
    spi_status_t status= sensor_read_register(LIS3DSH_WHO_AM_I_ADDR, &sensor_id);
    if(status == SPI_TIMEOUT)
    {
    	printf("Communication error\n");
    	for(;;){}
    }

    if(sensor_id != LIS3DSH_WHO_AM_I_VALUE)
    {
    	printf("Unexpected ID\n");
    	for (;;) {}
    }

    status = sensor_write_register(LIS3DSH_CTRL_REG4_ADDR, 0x5FU);
    if(status == SPI_TIMEOUT)
	{
		printf("Configuration error\n");
		for(;;){}
	}



    int16_t x_reading;
    uint32_t last_sample_tick = 0U;
    tilt_state_t tilt_state = TILT_LEVEL;

	for(;;)
	{
		if ((system_ticks - last_sample_tick) >= 100U)
		{
			last_sample_tick = system_ticks;
			status = sensor_read_x(&x_reading);

			if(status == SPI_TIMEOUT)
			{
				leds_show_level();
				printf("Timeout error\n");
				for(;;){}
			}

			if (tilt_state == TILT_LEVEL)
			{
				if (x_reading < -(TILT_THRESHOLD))
				{
					tilt_state = TILT_LEFT;
					leds_show_left();
				}
				else if(x_reading > TILT_THRESHOLD)
				{
					tilt_state = TILT_RIGHT;
					leds_show_right();
				}
				else
				{
					tilt_state = TILT_LEVEL;
					leds_show_level();
				}
			}

			else if (tilt_state == TILT_RIGHT)
			{
				if (x_reading < -(TILT_THRESHOLD))
				{
					tilt_state = TILT_LEFT;
					leds_show_left();
				}
				else if(x_reading <= TILT_RELEASE_THRESHOLD)
				{
					tilt_state = TILT_LEVEL;
					leds_show_level();
				}
			}

			else if (tilt_state == TILT_LEFT)
			{
				if (x_reading > (TILT_THRESHOLD))
				{
					tilt_state = TILT_RIGHT;
					leds_show_right();
				}
				else if(x_reading >= -(TILT_RELEASE_THRESHOLD))
				{
					tilt_state = TILT_LEVEL;
					leds_show_level();
				}
			}
		}
	}

}

void sensor_gpio_init(void)
{
	volatile uint32_t *pRCC_AHB1ENR = (uint32_t*)(RCC_BaseAddress + RCC_AHB1_Offset);
	*pRCC_AHB1ENR |= (1U << 0) | (1U << 4);

	volatile uint32_t *pGPIOE_BSRR = (uint32_t*)(GPIOE_BaseAddress + BSRR_Offset);
	*pGPIOE_BSRR = (1U << 3);

	volatile uint32_t *pGPIOA_Moder = (uint32_t*)(GPIOA_BaseAddress);
	*pGPIOA_Moder &= ~((3U << 10) | (3U << 12) | (3U << 14));
	*pGPIOA_Moder |= (2U << 10) | (2U << 12) | (2U << 14);

	volatile uint32_t *pGPIOE_Moder = (uint32_t*)(GPIOE_BaseAddress);
	*pGPIOE_Moder &= ~(3U << 6);
	*pGPIOE_Moder |= (1U << 6);

	volatile uint32_t *pGPIOA_AFRL = (uint32_t*)(GPIOA_BaseAddress + AFRL_Offset);
	*pGPIOA_AFRL &= ~((0xFU << 20) | (0xFU << 24) | (0xFU << 28));
	*pGPIOA_AFRL |= (5U << 20) | (5U << 24) | (5U << 28);

}

void spi1_init(void)
{
	volatile uint32_t *pRCC_APB2ENR = (uint32_t*)(RCC_BaseAddress + RCC_APB2_Offset);
	*pRCC_APB2ENR |= (1U << 12);

	volatile uint32_t *pSPI1_CR1 = (uint32_t*)(SPI1_BaseAddress);
	*pSPI1_CR1 &= ~(1U << 6);
	*pSPI1_CR1 |= (1U << 2);
	*pSPI1_CR1 &= ~(7U << 3);
	*pSPI1_CR1 |= (3U << 3);
	*pSPI1_CR1 |= (1U << 8) | (1U << 9);
	*pSPI1_CR1 |= (1U << 0) | (1U << 1);
	*pSPI1_CR1 &= ~((1U << 7) | (1U << 10) | (1U << 11) | (1U << 15));
	*pSPI1_CR1 |= (1U << 6);
}

spi_status_t spi1_transfer(uint8_t data, uint8_t *pReceived)
{
	volatile uint32_t *pSPI1_SR = (uint32_t*)(SPI1_BaseAddress + SPI1_SR_Offset);
	volatile uint8_t *pSPI1_DR = (uint8_t*)(SPI1_BaseAddress + SPI1_DR_Offset);

	uint32_t wait_start_tick = system_ticks;

	while((*pSPI1_SR & (1U << 1)) == 0)
	{
		if ((system_ticks - wait_start_tick) >= SPI_TIMEOUT_MS)
		{
			return SPI_TIMEOUT;

		}

	}
	*pSPI1_DR = data;

	wait_start_tick = system_ticks;

	while((*pSPI1_SR & (1U << 0)) == 0)
	{
		if ((system_ticks - wait_start_tick) >= SPI_TIMEOUT_MS)
		{
			return SPI_TIMEOUT;
		}
	}

	*pReceived = *pSPI1_DR;
	return SPI_OK;


}

void sensor_select(void)
{
	volatile uint32_t *pGPIOE_BSRR = (uint32_t*)(GPIOE_BaseAddress + BSRR_Offset);
	*pGPIOE_BSRR = (1U << 19);
}

spi_status_t sensor_deselect(void)
{
	volatile uint32_t *pSPI1_SR = (uint32_t*)(SPI1_BaseAddress + SPI1_SR_Offset);
	volatile uint32_t *pGPIOE_BSRR = (uint32_t*)(GPIOE_BaseAddress + BSRR_Offset);

	uint32_t wait_start_tick = system_ticks;

	while((*pSPI1_SR & (1U << 7)) != 0)
	{
		if ((system_ticks - wait_start_tick) >= SPI_TIMEOUT_MS)
		{
			*pGPIOE_BSRR = (1U << 3);
			return SPI_TIMEOUT;
		}

	}

	*pGPIOE_BSRR = (1U << 3);
	return SPI_OK;
}

spi_status_t sensor_read_register(uint8_t register_address,
                                  uint8_t *pValue)
{
	uint8_t discarded_byte;

	sensor_select();
	spi_status_t status = spi1_transfer(register_address | (1U << 7), &discarded_byte);

	if(status == SPI_TIMEOUT)
	{
		sensor_deselect();
		return status;
	}

	status = spi1_transfer(0x00U, pValue);

	if(status == SPI_TIMEOUT)
	{
		sensor_deselect();
		return status;
	}

	return sensor_deselect();

}

spi_status_t sensor_write_register(uint8_t register_address, uint8_t value)
{
	uint8_t discarded_byte;

	sensor_select();
	spi_status_t status = spi1_transfer(register_address & ~(1U << 7), &discarded_byte);

	if(status == SPI_TIMEOUT)
	{
		sensor_deselect();
		return status;
	}

	status = spi1_transfer(value, &discarded_byte);

	if(status == SPI_TIMEOUT)
	{
		sensor_deselect();
		return status;
	}

	return sensor_deselect();

}

spi_status_t sensor_read_x(int16_t *pX)
{
	uint8_t low;
	uint8_t high;

	spi_status_t status = sensor_read_register(LIS3DSH_OUT_X_L_ADDR, &low);

		if(status == SPI_TIMEOUT)
		{
			return status;
		}

		status = sensor_read_register(LIS3DSH_OUT_X_H_ADDR, &high);

		if(status == SPI_TIMEOUT)
		{
			return status;
		}

	*pX = (int16_t)(((uint16_t)high << 8) | low);
	return SPI_OK;
}

void systick_init(void)
{
	volatile uint32_t *pSTK_CTRL_Enable = (uint32_t*)(SYST_CSR_Address);
	*pSTK_CTRL_Enable &= ~(1U << 0);
	volatile uint32_t *pSTK_LOAD = (uint32_t*)(SYST_RVR_Address);
	*pSTK_LOAD = 15999U;
	volatile uint32_t *pSTK_VAL = (uint32_t*)(SYST_CVR_Address);
	*pSTK_VAL = 0U;

	*pSTK_CTRL_Enable |= (1U << 2) | (1U << 1) | (1U << 0);

}

void SysTick_Handler(void)
{
	system_ticks += 1;
}

void led_gpio_init(void)
{
	volatile uint32_t *pRCC_AHB1ENR_GPIODEN = (uint32_t*)(RCC_BaseAddress + RCC_AHB1_Offset);
	*pRCC_AHB1ENR_GPIODEN |= (1U << 3);

	volatile uint32_t *pGPIOD_BSRR = (uint32_t*)(GPIOx_BaseAddress + GPIOx_BSRR_Offset);
	*pGPIOD_BSRR = (1U << 28) | (1U << 30);

	volatile uint32_t *pGPIOD_Moder = (uint32_t*)(GPIOx_BaseAddress);
	*pGPIOD_Moder &= ~(3U << 24);
	*pGPIOD_Moder |= (1U << 24);
	*pGPIOD_Moder &= ~(3U << 28);
	*pGPIOD_Moder |= (1U << 28);

}
void leds_show_left(void)
{
	volatile uint32_t *pGPIOD_BSRR = (uint32_t*)(GPIOx_BaseAddress + GPIOx_BSRR_Offset);
	*pGPIOD_BSRR = (1U << 12) | (1U << 30);
}

void leds_show_right(void)
{
	volatile uint32_t *pGPIOD_BSRR = (uint32_t*)(GPIOx_BaseAddress + GPIOx_BSRR_Offset);
	*pGPIOD_BSRR = (1U << 28) | (1U << 14);
}

void leds_show_level(void)
{
	volatile uint32_t *pGPIOD_BSRR = (uint32_t*)(GPIOx_BaseAddress + GPIOx_BSRR_Offset);
	*pGPIOD_BSRR = (1U << 28) | (1U << 30);
}


